# Set the active profile here (change to 'prod' when deploying)
spring.profiles.active=dev
# Shared configurations
spring.application.name=shadow
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver